#!/usr/bin/env python 
#-*- coding: utf-8 -*-  

def main():
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"
    print "NANANANANANANANAN BATMAN!"


if __name__ == '__main__':
    main()
